name: dev-sql-01
enabled: true
connection_string: "Server=dev-sql-01.corp.example.com;Port=1433;Database=master;"
credential_id: "CREDENTIALS_VAULT-<YOUR_NONPROD_CREDENTIAL_ID>"
sql_server_logs_enabled: false
queries: []
